buildscript {
    repositories {
        maven { url 'https://plugins.gradle.org/m2/' }
        mavenCentral()
    }
    dependencies {
        classpath "net.serenity-bdd:serenity-gradle-plugin:4.2.8"
    }
}

plugins {
    id 'java'
}

apply plugin: 'net.serenity-bdd.serenity-gradle-plugin'

defaultTasks 'clean', 'test', 'aggregate'

group 'org.example'
version '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

ext {
    serenityVersion = '4.2.8'
    cucumberVersion = '7.18.0'
}

dependencies {
    testImplementation "net.serenity-bdd:serenity-core:${serenityVersion}"
    testImplementation "net.serenity-bdd:serenity-cucumber:${serenityVersion}"
    testImplementation "net.serenity-bdd:serenity-screenplay:${serenityVersion}"
    testImplementation "net.serenity-bdd:serenity-screenplay-webdriver:${serenityVersion}"
    testImplementation "io.cucumber:cucumber-java:${cucumberVersion}"
    testImplementation 'junit:junit:4.13.2'
}

test {
    systemProperties System.properties
}

serenity {
    reports = ['single-page-html']
}
